### ISSUE TITLE
no file 'CTR_O.p'

### ISSUE THREAD

**Issue by qpc1611094** [DZhaoXd/DT-ST#1]
Hello, thank you for your work. During training, I discovered that 'cityscapes_ b. py' requires' CTR '_ O. P 'file, but it is not provided.

**Comment by DZhaoXd** [comment]
Hello, thanks for your attention.  Please uncomment on lines 309-311 in train_TCR_DTU.py.
These codes generate CTR_O.p and CTR.p.

**Comment by qpc1611094** [comment]
Thanks, I get it!
