### ISSUE TITLE
About Cityscapes packages

### ISSUE THREAD

**Issue by zheangh** [DZhaoXd/DT-ST#3]
Thanks for sharing the wonderful work. 
On the download website of Cityscapes, there are many packages, and some are large. I am new to the segmentation of Cityscapes datasets, so I am not sure which ones I should download. Could you tell me which packages are needed for running your code? Thanks in advance!

**Comment by DZhaoXd** [comment]
Hi. The dataset can be downloaded from here. [gtFine_trainvaltest.zip](https://www.cityscapes-dataset.com/file-handling/?packageID=1) and [leftImg8bit_trainvaltest.zip (11GB)](https://www.cityscapes-dataset.com/file-handling/?packageID=3)
